# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zl1QELiTjH7Lj3Fp9A3fcaZIHpuv6JKk
"""

import pandas as pd
baza={
  "FIsh":["Maxsudov Inomjon", "Umarov Ali ","Abdullayev Mirjalol","Qadamova Zulayho","Rustamova Zebo","Almatova Mahliyo ","Nurmatov Axror"],
  "Yoshi":['25', '44', '38', '28', '30', '27', '26' ],
  "Manzili":[  'Fergona viloyati','Andijon viloyati','Namangan viloyati','Toshkent viloyati','Xorazm viloyati','Sirdaryo viloyati',"Namangan viloyati" ],
  "jinsi":['erkak','erkak','erkak','ayol','ayol','ayol','erkak'],
  "Ish joyi":['TATUFF','UBS','JQB','TATU','UBS','FARPI','FARDU']
}
db=pd.DataFrame(baza)
print(db)

filtr=db[(db['jinsi']=='ayol') & (db['Ish joyi']=='UBS') & (db['Yoshi']>'25')]
print(filtr)